-- =============================================
-- Seed gallery table with existing local photos
-- Run this AFTER schema.sql in Supabase SQL Editor
-- NOTE: These paths work locally (public/ folder).
-- For Vercel, upload via Admin Panel → Gallery tab instead.
-- =============================================

-- General photos (photo1.jpeg … photo222.jpeg)
INSERT INTO public.gallery (src, alt, category) VALUES
('/photo/photo1.jpeg','Photo 1','general'),('/photo/photo2.jpeg','Photo 2','general'),('/photo/photo3.jpeg','Photo 3','general'),
('/photo/photo4.jpeg','Photo 4','general'),('/photo/photo5.jpeg','Photo 5','general'),('/photo/photo6.jpeg','Photo 6','general'),
('/photo/photo7.jpeg','Photo 7','general'),('/photo/photo8.jpeg','Photo 8','general'),('/photo/photo9.jpeg','Photo 9','general'),
('/photo/photo10.jpeg','Photo 10','general'),('/photo/photo11.jpeg','Photo 11','general'),('/photo/photo12.jpeg','Photo 12','general'),
('/photo/photo13.jpeg','Photo 13','general'),('/photo/photo14.jpeg','Photo 14','general'),('/photo/photo15.jpeg','Photo 15','general'),
('/photo/photo16.jpeg','Photo 16','general'),('/photo/photo17.jpeg','Photo 17','general'),('/photo/photo18.jpeg','Photo 18','general'),
('/photo/photo19.jpeg','Photo 19','general'),('/photo/photo20.jpeg','Photo 20','general'),('/photo/photo21.jpeg','Photo 21','general'),
('/photo/photo22.jpeg','Photo 22','general'),('/photo/photo23.jpeg','Photo 23','general'),('/photo/photo24.jpeg','Photo 24','general'),
('/photo/photo25.jpeg','Photo 25','general'),('/photo/photo26.jpeg','Photo 26','general'),('/photo/photo27.jpeg','Photo 27','general'),
('/photo/photo28.jpeg','Photo 28','general'),('/photo/photo29.jpeg','Photo 29','general'),('/photo/photo30.jpeg','Photo 30','general'),
('/photo/photo31.jpeg','Photo 31','general'),('/photo/photo32.jpeg','Photo 32','general'),('/photo/photo33.jpeg','Photo 33','general'),
('/photo/photo34.jpeg','Photo 34','general'),('/photo/photo35.jpeg','Photo 35','general'),('/photo/photo36.jpeg','Photo 36','general'),
('/photo/photo37.jpeg','Photo 37','general'),('/photo/photo38.jpeg','Photo 38','general'),('/photo/photo39.jpeg','Photo 39','general'),
('/photo/photo40.jpeg','Photo 40','general'),('/photo/photo41.jpeg','Photo 41','general'),('/photo/photo42.jpeg','Photo 42','general'),
('/photo/photo43.jpeg','Photo 43','general'),('/photo/photo44.jpeg','Photo 44','general'),('/photo/photo45.jpeg','Photo 45','general'),
('/photo/photo46.jpeg','Photo 46','general'),('/photo/photo47.jpeg','Photo 47','general'),('/photo/photo48.jpeg','Photo 48','general'),
('/photo/photo49.jpeg','Photo 49','general'),('/photo/photo50.jpeg','Photo 50','general'),('/photo/photo51.jpeg','Photo 51','general'),
('/photo/photo52.jpeg','Photo 52','general'),('/photo/photo53.jpeg','Photo 53','general'),('/photo/photo54.jpeg','Photo 54','general'),
('/photo/photo55.jpeg','Photo 55','general'),('/photo/photo56.jpeg','Photo 56','general'),('/photo/photo57.jpeg','Photo 57','general'),
('/photo/photo58.jpeg','Photo 58','general'),('/photo/photo59.jpeg','Photo 59','general'),('/photo/photo60.jpeg','Photo 60','general'),
('/photo/photo61.jpeg','Photo 61','general'),('/photo/photo62.jpeg','Photo 62','general'),('/photo/photo63.jpeg','Photo 63','general'),
('/photo/photo64.jpeg','Photo 64','general'),('/photo/photo65.jpeg','Photo 65','general'),('/photo/photo66.jpeg','Photo 66','general'),
('/photo/photo67.jpeg','Photo 67','general'),('/photo/photo68.jpeg','Photo 68','general'),('/photo/photo69.jpeg','Photo 69','general'),
('/photo/photo70.jpeg','Photo 70','general'),('/photo/photo71.jpeg','Photo 71','general'),('/photo/photo72.jpeg','Photo 72','general'),
('/photo/photo73.jpeg','Photo 73','general'),('/photo/photo74.jpeg','Photo 74','general'),('/photo/photo75.jpeg','Photo 75','general'),
('/photo/photo76.jpeg','Photo 76','general'),('/photo/photo77.jpeg','Photo 77','general'),('/photo/photo78.jpeg','Photo 78','general'),
('/photo/photo79.jpeg','Photo 79','general'),('/photo/photo80.jpeg','Photo 80','general'),('/photo/photo81.jpeg','Photo 81','general'),
('/photo/photo82.jpeg','Photo 82','general'),('/photo/photo83.jpeg','Photo 83','general'),('/photo/photo84.jpeg','Photo 84','general'),
('/photo/photo85.jpeg','Photo 85','general'),('/photo/photo86.jpeg','Photo 86','general'),('/photo/photo87.jpeg','Photo 87','general'),
('/photo/photo88.jpeg','Photo 88','general'),('/photo/photo89.jpeg','Photo 89','general'),('/photo/photo90.jpeg','Photo 90','general'),
('/photo/photo91.jpeg','Photo 91','general'),('/photo/photo92.jpeg','Photo 92','general'),('/photo/photo93.jpeg','Photo 93','general'),
('/photo/photo94.jpeg','Photo 94','general'),('/photo/photo95.jpeg','Photo 95','general'),('/photo/photo96.jpeg','Photo 96','general'),
('/photo/photo97.jpeg','Photo 97','general'),('/photo/photo98.jpeg','Photo 98','general'),('/photo/photo99.jpeg','Photo 99','general'),
('/photo/photo100.jpeg','Photo 100','general'),('/photo/photo101.jpeg','Photo 101','general'),('/photo/photo102.jpeg','Photo 102','general'),
('/photo/photo103.jpeg','Photo 103','general'),('/photo/photo104.jpeg','Photo 104','general'),('/photo/photo105.jpeg','Photo 105','general'),
('/photo/photo106.jpeg','Photo 106','general'),('/photo/photo107.jpeg','Photo 107','general'),('/photo/photo108.jpeg','Photo 108','general'),
('/photo/photo109.jpeg','Photo 109','general'),('/photo/photo110.jpeg','Photo 110','general'),('/photo/photo111.jpeg','Photo 111','general'),
('/photo/photo112.jpeg','Photo 112','general'),('/photo/photo113.jpeg','Photo 113','general'),('/photo/photo114.jpeg','Photo 114','general'),
('/photo/photo115.jpeg','Photo 115','general'),('/photo/photo116.jpeg','Photo 116','general'),('/photo/photo117.jpeg','Photo 117','general'),
('/photo/photo118.jpeg','Photo 118','general'),('/photo/photo119.jpeg','Photo 119','general'),('/photo/photo120.jpeg','Photo 120','general'),
('/photo/photo121.jpeg','Photo 121','general'),('/photo/photo122.jpeg','Photo 122','general'),('/photo/photo123.jpeg','Photo 123','general'),
('/photo/photo124.jpeg','Photo 124','general'),('/photo/photo125.jpeg','Photo 125','general'),('/photo/photo126.jpeg','Photo 126','general'),
('/photo/photo127.jpeg','Photo 127','general'),('/photo/photo128.jpeg','Photo 128','general'),('/photo/photo129.jpeg','Photo 129','general'),
('/photo/photo130.jpeg','Photo 130','general'),('/photo/photo131.jpeg','Photo 131','general'),('/photo/photo132.jpeg','Photo 132','general'),
('/photo/photo133.jpeg','Photo 133','general'),('/photo/photo134.jpeg','Photo 134','general'),('/photo/photo135.jpeg','Photo 135','general'),
('/photo/photo136.jpeg','Photo 136','general'),('/photo/photo137.jpeg','Photo 137','general'),('/photo/photo138.jpeg','Photo 138','general'),
('/photo/photo139.jpeg','Photo 139','general'),('/photo/photo140.jpeg','Photo 140','general'),('/photo/photo141.jpeg','Photo 141','general'),
('/photo/photo142.jpeg','Photo 142','general'),('/photo/photo143.jpeg','Photo 143','general'),('/photo/photo144.jpeg','Photo 144','general'),
('/photo/photo145.jpeg','Photo 145','general'),('/photo/photo146.jpeg','Photo 146','general'),('/photo/photo147.jpeg','Photo 147','general'),
('/photo/photo148.jpeg','Photo 148','general'),('/photo/photo149.jpeg','Photo 149','general'),('/photo/photo150.jpeg','Photo 150','general'),
('/photo/photo151.jpeg','Photo 151','general'),('/photo/photo152.jpeg','Photo 152','general'),('/photo/photo153.jpeg','Photo 153','general'),
('/photo/photo154.jpeg','Photo 154','general'),('/photo/photo155.jpeg','Photo 155','general'),('/photo/photo156.jpeg','Photo 156','general'),
('/photo/photo157.jpeg','Photo 157','general'),('/photo/photo158.jpeg','Photo 158','general'),('/photo/photo159.jpeg','Photo 159','general'),
('/photo/photo160.jpeg','Photo 160','general'),('/photo/photo161.jpeg','Photo 161','general'),('/photo/photo162.jpeg','Photo 162','general'),
('/photo/photo163.jpeg','Photo 163','general'),('/photo/photo164.jpeg','Photo 164','general'),('/photo/photo165.jpeg','Photo 165','general'),
('/photo/photo166.jpeg','Photo 166','general'),('/photo/photo167.jpeg','Photo 167','general'),('/photo/photo168.jpeg','Photo 168','general'),
('/photo/photo169.jpeg','Photo 169','general'),('/photo/photo170.jpeg','Photo 170','general'),('/photo/photo171.jpeg','Photo 171','general'),
('/photo/photo172.jpeg','Photo 172','general'),('/photo/photo173.jpeg','Photo 173','general'),('/photo/photo174.jpeg','Photo 174','general'),
('/photo/photo175.jpeg','Photo 175','general'),('/photo/photo176.jpeg','Photo 176','general'),('/photo/photo177.jpeg','Photo 177','general'),
('/photo/photo178.jpeg','Photo 178','general'),('/photo/photo179.jpeg','Photo 179','general'),('/photo/photo180.jpeg','Photo 180','general'),
('/photo/photo181.jpeg','Photo 181','general'),('/photo/photo182.jpeg','Photo 182','general'),('/photo/photo183.jpeg','Photo 183','general'),
('/photo/photo184.jpeg','Photo 184','general'),('/photo/photo185.jpeg','Photo 185','general'),('/photo/photo186.jpeg','Photo 186','general'),
('/photo/photo187.jpeg','Photo 187','general'),('/photo/photo188.jpeg','Photo 188','general'),('/photo/photo189.jpeg','Photo 189','general'),
('/photo/photo190.jpeg','Photo 190','general'),('/photo/photo191.jpeg','Photo 191','general'),('/photo/photo192.jpeg','Photo 192','general'),
('/photo/photo193.jpeg','Photo 193','general'),('/photo/photo194.jpeg','Photo 194','general'),('/photo/photo195.jpeg','Photo 195','general'),
('/photo/photo196.jpeg','Photo 196','general'),('/photo/photo197.jpeg','Photo 197','general'),('/photo/photo198.jpeg','Photo 198','general'),
('/photo/photo199.jpeg','Photo 199','general'),('/photo/photo200.jpeg','Photo 200','general'),('/photo/photo201.jpeg','Photo 201','general'),
('/photo/photo202.jpeg','Photo 202','general'),('/photo/photo203.jpeg','Photo 203','general'),('/photo/photo204.jpeg','Photo 204','general'),
('/photo/photo205.jpeg','Photo 205','general'),('/photo/photo206.jpeg','Photo 206','general'),('/photo/photo207.jpeg','Photo 207','general'),
('/photo/photo208.jpeg','Photo 208','general'),('/photo/photo209.jpeg','Photo 209','general'),('/photo/photo210.jpeg','Photo 210','general'),
('/photo/photo211.jpeg','Photo 211','general'),('/photo/photo212.jpeg','Photo 212','general'),('/photo/photo213.jpeg','Photo 213','general'),
('/photo/photo214.jpeg','Photo 214','general'),('/photo/photo215.jpeg','Photo 215','general'),('/photo/photo216.jpeg','Photo 216','general'),
('/photo/photo217.jpeg','Photo 217','general'),('/photo/photo218.jpeg','Photo 218','general'),('/photo/photo219.jpeg','Photo 219','general'),
('/photo/photo220.jpeg','Photo 220','general'),('/photo/photo221.jpeg','Photo 221','general'),('/photo/photo222.jpeg','Photo 222','general');

-- Student photos (from public/students/ folder)
INSERT INTO public.gallery (src, alt, category) VALUES
('/students/student1.jpg','Student 1','students'),
('/students/student2.jpg','Student 2','students'),
('/students/student3.jpg','Student 3','students'),
('/students/student4.jpg','Student 4','students'),
('/students/student5.jpg','Student 5','students'),
('/students/student6.png','Student 6','students'),
('/students/student7.png','Student 7','students'),
('/students/student8.jpg','Student 8','students'),
('/students/student9.jpg','Student 9','students'),
('/students/student10.jpg','Student 10','students'),
('/students/student11.jpg','Student 11','students'),
('/students/student12.jpg','Student 12','students'),
('/students/student13.jpg','Student 13','students'),
('/students/student14.jpg','Student 14','students'),
('/students/student15.jpg','Student 15','students'),
('/students/student16.jpg','Student 16','students'),
('/students/student17.jpg','Student 17','students'),
('/students/student18.jpg','Student 18','students'),
('/students/student19.jpg','Student 19','students'),
('/students/student20.jpg','Student 20','students'),
('/students/student21.jpg','Student 21','students'),
('/students/student22.jpg','Student 22','students'),
('/students/student23.jpg','Student 23','students'),
('/students/student24.jpg','Student 24','students'),
('/students/student25.jpg','Student 25','students'),
('/students/student26.jpg','Student 26','students'),
('/students/student27.jpg','Student 27','students'),
('/students/student28.jpg','Student 28','students'),
('/students/student29.jpg','Student 29','students'),
('/students/student30.jpg','Student 30','students'),
('/students/student31.jpg','Student 31','students'),
('/students/student32.jpg','Student 32','students'),
('/students/student33.jpg','Student 33','students'),
('/students/student34.jpg','Student 34','students'),
('/students/student35.jpg','Student 35','students'),
('/students/student36.jpg','Student 36','students'),
('/students/student37.jpg','Student 37','students'),
('/students/student38.jpg','Student 38','students'),
('/students/student39.jpg','Student 39','students'),
('/students/student40.jpg','Student 40','students'),
('/students/student41.jpg','Student 41','students'),
('/students/student42.jpg','Student 42','students'),
('/students/student43.jpeg','Student 43','students');

-- Achievement photos (from public/achiment/ folder)
INSERT INTO public.gallery (src, alt, category) VALUES
('/achiment/achievement1.jpeg','Achievement 1','achievements'),
('/achiment/achievement2.jpeg','Achievement 2','achievements'),
('/achiment/achievement3.jpeg','Achievement 3','achievements'),
('/achiment/achievement4.jpeg','Achievement 4','achievements'),
('/achiment/achievement5.jpeg','Achievement 5','achievements'),
('/achiment/achievement6.jpeg','Achievement 6','achievements'),
('/achiment/achievement7.jpeg','Achievement 7','achievements'),
('/achiment/achievement8.jpeg','Achievement 8','achievements'),
('/achiment/achievement9.jpeg','Achievement 9','achievements'),
('/achiment/achievement10.jpeg','Achievement 10','achievements'),
('/achiment/achievement11.jpeg','Achievement 11','achievements'),
('/achiment/achievement12.jpeg','Achievement 12','achievements'),
('/achiment/achievement13.jpeg','Achievement 13','achievements'),
('/achiment/achievement14.jpeg','Achievement 14','achievements'),
('/achiment/achievement15.jpeg','Achievement 15','achievements'),
('/achiment/achievement16.jpg','Achievement 16','achievements'),
('/achiment/achievement17.jpeg','Achievement 17','achievements'),
('/achiment/achievement18.jpeg','Achievement 18','achievements'),
('/achiment/achievement19.jpeg','Achievement 19','achievements'),
('/achiment/achievement20.jpeg','Achievement 20','achievements'),
('/achiment/achievement21.jpeg','Achievement 21','achievements'),
('/achiment/achievement22.jpeg','Achievement 22','achievements'),
('/achiment/achievement23.jpeg','Achievement 23','achievements'),
('/achiment/achievement24.jpeg','Achievement 24','achievements'),
('/achiment/achievement25.jpeg','Achievement 25','achievements'),
('/achiment/achievement26.jpeg','Achievement 26','achievements'),
('/achiment/achievement27.jpeg','Achievement 27','achievements'),
('/achiment/achievement28.jpeg','Achievement 28','achievements'),
('/achiment/achievement29.jpeg','Achievement 29','achievements'),
('/achiment/achievement30.jpeg','Achievement 30','achievements'),
('/achiment/achievement31.jpeg','Achievement 31','achievements'),
('/achiment/achievement32.jpeg','Achievement 32','achievements'),
('/achiment/achievement33.jpeg','Achievement 33','achievements'),
('/achiment/achievement34.jpeg','Achievement 34','achievements'),
('/achiment/achievement35.jpeg','Achievement 35','achievements'),
('/achiment/achievement36.jpeg','Achievement 36','achievements');
