/**
 * GALLERY — extra photos (gallery.html loads these automatically)
 * Add photos with add-helper.html, then paste the generated line below.
 */
window.VIDYA_GALLERY = [
    // Example:
    // { src: 'photo/photo201.jpeg', alt: 'Annual day 2026', cat: 'general' },


{ src: 'photo/photo1.jpeg', alt: 'Photo1', cat: 'general' },
{ src: 'photo/photo2.jpeg', alt: 'Photo2', cat: 'general' },
{ src: 'photo/photo3.jpeg', alt: 'Photo3', cat: 'general' },
{ src: 'photo/photo4.jpeg', alt: 'Photo4', cat: 'general' },
{ src: 'photo/photo5.jpeg', alt: 'Photo5', cat: 'general' },
{ src: 'photo/photo6.jpeg', alt: 'Photo6', cat: 'general' },
{ src: 'photo/photo7.jpeg', alt: 'Photo7', cat: 'general' },
{ src: 'photo/photo8.jpeg', alt: 'Photo8', cat: 'general' },
{ src: 'photo/photo9.jpeg', alt: 'Photo9', cat: 'general' },
{ src: 'photo/photo10.jpeg', alt: 'Photo10', cat: 'general' },
{ src: 'photo/photo11.jpeg', alt: 'Photo11', cat: 'general' },
{ src: 'photo/photo12.jpeg', alt: 'Photo12', cat: 'general' },
{ src: 'photo/photo13.jpeg', alt: 'Photo13', cat: 'general' },
{ src: 'photo/photo14.jpeg', alt: 'Photo14', cat: 'general' },
{ src: 'photo/photo15.jpeg', alt: 'Photo15', cat: 'general' },
{ src: 'photo/photo16.jpeg', alt: 'Photo16', cat: 'general' },
{ src: 'photo/photo17.jpeg', alt: 'Photo17', cat: 'general' },
{ src: 'photo/photo18.jpeg', alt: 'Photo18', cat: 'general' },
{ src: 'photo/photo19.jpeg', alt: 'Photo19', cat: 'general' },
{ src: 'photo/photo20.jpeg', alt: 'Photo20', cat: 'general' },
{ src: 'photo/photo21.jpeg', alt: 'Photo21', cat: 'general' },
{ src: 'photo/photo22.jpeg', alt: 'Photo22', cat: 'general' },
{ src: 'photo/photo23.jpeg', alt: 'Photo23', cat: 'general' },
{ src: 'photo/photo24.jpeg', alt: 'Photo24', cat: 'general' },
{ src: 'photo/photo25.jpeg', alt: 'Photo25', cat: 'general' },
{ src: 'photo/photo26.jpeg', alt: 'Photo26', cat: 'general' },
{ src: 'photo/photo27.jpeg', alt: 'Photo27', cat: 'general' },
{ src: 'photo/photo28.jpeg', alt: 'Photo28', cat: 'general' },
{ src: 'photo/photo29.jpeg', alt: 'Photo29', cat: 'general' },
{ src: 'photo/photo30.jpeg', alt: 'Photo30', cat: 'general' },
{ src: 'photo/photo31.jpeg', alt: 'Photo31', cat: 'general' },
{ src: 'photo/photo32.jpeg', alt: 'Photo32', cat: 'general' },
{ src: 'photo/photo33.jpeg', alt: 'Photo33', cat: 'general' },
{ src: 'photo/photo34.jpeg', alt: 'Photo34', cat: 'general' },
{ src: 'photo/photo35.jpeg', alt: 'Photo35', cat: 'general' },
{ src: 'photo/photo36.jpeg', alt: 'Photo36', cat: 'general' },
{ src: 'photo/photo37.jpeg', alt: 'Photo37', cat: 'general' },
{ src: 'photo/photo38.jpeg', alt: 'Photo38', cat: 'general' },
{ src: 'photo/photo39.jpeg', alt: 'Photo39', cat: 'general' },
{ src: 'photo/photo40.jpeg', alt: 'Photo40', cat: 'general' },
{ src: 'photo/photo41.jpeg', alt: 'Photo41', cat: 'general' },
{ src: 'photo/photo42.jpeg', alt: 'Photo42', cat: 'general' },
{ src: 'photo/photo43.jpeg', alt: 'Photo43', cat: 'general' },
{ src: 'photo/photo44.jpeg', alt: 'Photo44', cat: 'general' },
{ src: 'photo/photo45.jpeg', alt: 'Photo45', cat: 'general' },
{ src: 'photo/photo46.jpeg', alt: 'Photo46', cat: 'general' },
{ src: 'photo/photo47.jpeg', alt: 'Photo47', cat: 'general' },
{ src: 'photo/photo48.jpeg', alt: 'Photo48', cat: 'general' },
{ src: 'photo/photo49.jpeg', alt: 'Photo49', cat: 'general' },
{ src: 'photo/photo50.jpeg', alt: 'Photo50', cat: 'general' },
{ src: 'photo/photo51.jpeg', alt: 'Photo51', cat: 'general' },
{ src: 'photo/photo52.jpeg', alt: 'Photo52', cat: 'general' },
{ src: 'photo/photo53.jpeg', alt: 'Photo53', cat: 'general' },
{ src: 'photo/photo54.jpeg', alt: 'Photo54', cat: 'general' },
{ src: 'photo/photo55.jpeg', alt: 'Photo55', cat: 'general' },
{ src: 'photo/photo56.jpeg', alt: 'Photo56', cat: 'general' },
{ src: 'photo/photo57.jpeg', alt: 'Photo57', cat: 'general' },
{ src: 'photo/photo58.jpeg', alt: 'Photo58', cat: 'general' },
{ src: 'photo/photo59.jpeg', alt: 'Photo59', cat: 'general' },
{ src: 'photo/photo60.jpeg', alt: 'Photo60', cat: 'general' },
{ src: 'photo/photo61.jpeg', alt: 'Photo61', cat: 'general' },
{ src: 'photo/photo62.jpeg', alt: 'Photo62', cat: 'general' },
{ src: 'photo/photo63.jpeg', alt: 'Photo63', cat: 'general' },
{ src: 'photo/photo64.jpeg', alt: 'Photo64', cat: 'general' },
{ src: 'photo/photo65.jpeg', alt: 'Photo65', cat: 'general' },
{ src: 'photo/photo66.jpeg', alt: 'Photo66', cat: 'general' },
{ src: 'photo/photo67.jpeg', alt: 'Photo67', cat: 'general' },
{ src: 'photo/photo68.jpeg', alt: 'Photo68', cat: 'general' },
{ src: 'photo/photo69.jpeg', alt: 'Photo69', cat: 'general' },
{ src: 'photo/photo70.jpeg', alt: 'Photo70', cat: 'general' },
{ src: 'photo/photo71.jpeg', alt: 'Photo71', cat: 'general' },
{ src: 'photo/photo72.jpeg', alt: 'Photo72', cat: 'general' },
{ src: 'photo/photo73.jpeg', alt: 'Photo73', cat: 'general' },
{ src: 'photo/photo74.jpeg', alt: 'Photo74', cat: 'general' },
{ src: 'photo/photo75.jpeg', alt: 'Photo75', cat: 'general' },
{ src: 'photo/photo76.jpeg', alt: 'Photo76', cat: 'general' },
{ src: 'photo/photo77.jpeg', alt: 'Photo77', cat: 'general' },
{ src: 'photo/photo78.jpeg', alt: 'Photo78', cat: 'general' },
{ src: 'photo/photo79.jpeg', alt: 'Photo79', cat: 'general' },
{ src: 'photo/photo80.jpeg', alt: 'Photo80', cat: 'general' },
{ src: 'photo/photo81.jpeg', alt: 'Photo81', cat: 'general' },
{ src: 'photo/photo82.jpeg', alt: 'Photo82', cat: 'general' },
{ src: 'photo/photo83.jpeg', alt: 'Photo83', cat: 'general' },
{ src: 'photo/photo84.jpeg', alt: 'Photo84', cat: 'general' },
{ src: 'photo/photo85.jpeg', alt: 'Photo85', cat: 'general' },
{ src: 'photo/photo86.jpeg', alt: 'Photo86', cat: 'general' },
{ src: 'photo/photo87.jpeg', alt: 'Photo87', cat: 'general' },
{ src: 'photo/photo88.jpeg', alt: 'Photo88', cat: 'general' },
{ src: 'photo/photo89.jpeg', alt: 'Photo89', cat: 'general' },
{ src: 'photo/photo90.jpeg', alt: 'Photo90', cat: 'general' },
{ src: 'photo/photo91.jpeg', alt: 'Photo91', cat: 'general' },
{ src: 'photo/photo92.jpeg', alt: 'Photo92', cat: 'general' },
{ src: 'photo/photo93.jpeg', alt: 'Photo93', cat: 'general' },
{ src: 'photo/photo94.jpeg', alt: 'Photo94', cat: 'general' },
{ src: 'photo/photo95.jpeg', alt: 'Photo95', cat: 'general' },
{ src: 'photo/photo96.jpeg', alt: 'Photo96', cat: 'general' },
{ src: 'photo/photo97.jpeg', alt: 'Photo97', cat: 'general' },
{ src: 'photo/photo98.jpeg', alt: 'Photo98', cat: 'general' },
{ src: 'photo/photo99.jpeg', alt: 'Photo99', cat: 'general' },
{ src: 'photo/photo100.jpeg', alt: 'Photo100', cat: 'general' }


];
